//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATBAN
    {
        public int MADATBAN { get; set; }
        public Nullable<int> MAKH { get; set; }
        public Nullable<int> MABA { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public Nullable<int> GIODAT { get; set; }
        public Nullable<int> SLKHACH { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
