//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhaHang_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANQUYEN
    {
        public int MANV { get; set; }
        public int IDCHUCNANG { get; set; }
        public string GHICHU { get; set; }
    
        public virtual CHUCNANG CHUCNANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
